env: "local"
storage_path: "./storage/storage.db"
database_url: "postgres://url_user:password@localhost:5432/urlshortener?sslmode=disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
